added syncing linear slides and terminology
dr-hextanium/cookbook pull request #13
Opened 2024-01-27 21:31 UTC by RuckusRoboticsCode

2024-02-01 12:37 UTC, dr-hextanium requested changes

2024-02-01 12:37 UTC, dr-hextanium commented on src/syncing_two_linear_slide_motors_using_a_pidf_controller.md
> +Linear slides powered by two different motors can end up twisted, with one slide higher than the other. This can happen if the two encoders get out of sync. If you are using the RUN_TO_POSITION motor
fix: typo at "if you are using a PIDF controlleron each motor"

2024-02-01 12:37 UTC, dr-hextanium commented on src/syncing_two_linear_slide_motors_using_a_pidf_controller.md
> +**The BEST way to keep these in sync is to have them be mechanically connected with a bar or a piece of channel. If the two act as one rigid body, then it is a lot less dependent on software. However
refactor: "However, this is not always possible" (omission of "we")

2024-02-01 12:37 UTC, dr-hextanium commented on src/terminology_and_acronyms.md
> +# Acronyms
love this cute lil section

2024-02-01 18:47 UTC, RuckusRoboticsCode commented
Okay, I made the edits and shifted code blocks into java files. The indentation is a little weird, but it's fine.

2024-02-02 01:35 UTC, dr-hextanium commented
im going to assume that this builds as is

2024-02-02 01:35 UTC, merged